"""empty message

Revision ID: 36965f7940e2
Revises: 0f97a191b271
Create Date: 2024-04-22 13:32:10.184238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36965f7940e2'
down_revision = '0f97a191b271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_logs', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
